### ISSUE TITLE
cython integration

### ISSUE THREAD

**Issue by hartsantler** [secureosv/pythia#5]
cython can output c++ and can help simplify integration with CPython.

* support pyx files
* insert pythia c++ into cython build
* support some cython syntax, like `cdef`
* allow pythia c++ to directly call cython functions.

**Comment by hartsantler** [comment]
```bash
brett@mintx /tmp $ ./myexe 
init CPython...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named mycython_module
checking __builtins__
run_test
ERROR
Segmentation fault
brett@mintx /tmp $ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mycython_module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initmycython_module)
>>> 
```

**Comment by hartsantler** [comment]
http://stackoverflow.com/questions/24226001/importerror-dynamic-module-does-not-define-init-function-initfizzbuzz
